### ISSUE TITLE
Sass By Example

### ISSUE THREAD

**Issue by aunmro** [aunmro/aunmro.github.io#3]
Sass 是 CSS 预处理器，为 CSS 提供了变量，嵌套，引用，函数等功能，让前端工程师更方便地写 CSS。
## 安装
1. Sass 官方实现
   
   Sass 的官方实现是使用 Ruby 代码编写，因此你需要安装 Ruby 及包管理 gem。
   - Windows 用户直接下载安装 Ruby 后在命令行执行 `gem install sass`。
   - linux 下如果你使用 rvm 则 `gem install sass`，普通安装则`sudo gem install sass`。
2. `libsass`
   
   libsass 是 sass 的分支，设计为其他语言的使用者使用，比如
   [node-sass](https://github.com/sass/node-sass)。官网列出了其他语言的实现：
   http://sass-lang.com/libsass
3. 编辑器
   
   Sublime，bracket 等编辑器有自动编译插件。
4. 自动化构建工具, `Rails` `Fis` 等提供了自动编译功能
## 使用命令行

编译命令：`sass input.scss output.css` `sass input.sass output.css`

Sass 支持`.sass` `.scss` 两种语法，scss 接近于原生 css 风格，sass
则使用缩进风格。

<h2 align="center">基本用法</h2>

## 注释

`//单行注释，并且不会编译为css注释`

`/*注释 会编译为css*/`

one.sass

``` sass
//不会被编译
```

执行`sass one.sass one.css`,生成的 one.css 是空白的

---

one.scss

``` scss
/*css注释*/
```

执行`sass one.scss one.css`,生成 one.css

``` css
@charset "UTF-8";
/*css注释*/
```
## 嵌套

scss 语法

``` scss
p {
  font-size: 1.5em;
  .inline-box {font-size: 1.3em;}
}
```

sass 采用缩进语法

``` sass
p
  font-size: 1.5em
  .inline-box
    font-size: 1.3em
```

输出

``` css
p {font-size: 1.5em;}
p .inline-box {font-size: 1.3em;}
```
## `&` 引用父类元素，实现`a:hover`等功能

``` scss
a {
  color: cornflowerblue;
  &:hover {color: chocolate;}
}
```

``` sass
a
  color: cornflowerblue
  &:hover
    color: chocolate
```

输出

``` css
a {color: cornflowerblue;}
a:hover {color: chocolate;}
```
## 属性嵌套

scss

``` scss
.main-content {
  font: {
    size: 1.1rem;
    style: oblique;
  }
}
```

sass

``` sass
.main-content
  font:
    size: 1.1rem
    style: oblique
```

输出

``` css
.main-content {
  font-size: 1.1rem;
  font-style: oblique;
}
```
## 导入

scss

``` scss
@import 'one';
```

sass 导入不需要带引号

``` sass
@import one
```
1. 2导入文件名可以是`_one.scss` `one.scss` `one.sass` `_one.sass`。
2. 以下划线开头的是局部 sass 模板，不会被生成为 css 。
3. **scss 可以引入 sass 文件,反之亦可**。
4. 插入css文件则需要带上后缀，`@import 'base.css'`。

``` scss
//_one.scss
p {font-size: 2rem;}
```

输出

``` css
p {font-size: 2rem;}
```
## 变量

scss

``` scss
$color: red;
p {color: $color;}
```

sass

``` sass
$color: red
p
  color: $color
```

**变量可以多值**，比如`$font: Helvetica, sans-serif`
## Mixin 混入

Mixin 的 sass 语法 和 scss 语法差异比较大

``` scss
@mixin font-value($key, $value) {
  font-#{$key}: $value;
}

p {@include font-value(size, 2rem);}
```

``` sass
=font-value($key, $value)
  font-#{$key}: $value

p
  +font-value(size, 2rem)
```

输出

``` css
p {font-size: 2rem;}
```
## 扩展继承

scss

``` scss
.message {font-style: italic;}

.error {
  @extend .message;
  color: red;
}
```

sass

``` sass
.message
  font-style: italic

.error
  @extend .message
  color: red
```

输出

``` css
.message, .error {font-style: italic;}
.error {color: red;}
```
## 运算

sass 支持 + - \* / % == != >= <=等运算

``` sass
body {width: 100%;}

article {
  float: left;
  width: 600px / 960px * 100%;
}

aside {
  float: right;
  width: 300px / 960px * 100%;
}
```

输出

``` css
body {width: 100%;}

article {
  float: left;
  width: 62.5%;
}

aside {
  float: right;
  width: 31.25%;
}
```
## 字符串

`"var" 'var' var` 单引号，双引号，无引号都被归入字符串类型

sass

``` sass
=font-size($px, $type)
  font-size: $px $type

p
  +font-size(10, px)
```

<h2 align="center">高级用法</h2>

## list 数组

scss

``` scss
$color: red, blue;
$px: (800px, 600px), (1366px, 768px);

//用 nth 函数操作
a {
  color: nth($color, 1);
  &:hover {color: nth($color, 2);}
  font-size: nth(nth($px, 2), 1)
}
```
1. `()` 表示二维数组
2. ntn 函数取出数组的值，**list 从 1 开始**

输出

``` css
a {
  color: red;
  font-size: 1366px;
}
a:hover {color: blue;}
```
## map 字典

``` scss
$px: (pc: 1366px, phone: 400px);
p {width: map-get($px, pc);} // map 函数
```

`map-get()` 函数获取字典的值

``` css
p {width: 1366px;}
```
## colors

Sass 提供了大量的色彩变量
https://github.com/sass/sass/blob/stable/lib/sass/script/value/color.rb#L28-L180

**色彩同样可以计算**

``` scss
p {
  color: #010203 + #040506;
}
```

rgba 函数

``` scss
p {
  color: rgba(255, 0, 0, 0.75) + rgba(0, 255, 0, 0.75);
}
```

hsl 函数

``` scss
p {
  color: hsl(0, 100%, 50%);
}
```
## 函数同样可以使用关键字参数

``` scss
p {
  color: hsl($hue: 0, $saturation: 100%, $lightness: 50%);
}
```
## `#{}`

输出变量值

``` scss
$value: size;

p {font-#{$value}: 2rem;}
```

输出

``` css
p {font-size: 2rem;}
```
## 内部函数

http://sass-lang.com/documentation/Sass/Script/Functions.html
## `!default` 若变量不存在则赋予变量值，否则无效

``` scss
$one: 1 !default;

$two: 2;
$two: "二" !default;

p {
  font-size: $one;

  a {font-size: $two;}
}
```

第二次 $two 不会被赋值

<h2 align="center">控制结构</h2>

## `@if` `@else`

``` scss
p {
  $px: 800px;
  @if $px > 500 {font-size: 1.3rem;}
  @else {font-size: 0.8rem;}
}
```
## `@for`循环
1. `@for $var from i through end` `through` 包括 end值
   
   ``` scss
   @for $i from 1 through 5 {
     .item#{$i} {font-size: 0.8rem *$i;}
   }
   ```
   
   ``` css
   .item1 {
     font-size: 0.8rem; }
   
   .item2 {
     font-size: 1.6rem; }
   
   .item3 {
     font-size: 2.4rem; }
   
   .item4 {
     font-size: 3.2rem; }
   
   .item5 {
     font-size: 4rem; }
   ```
2. `@for $var from i to end` 不包含 end 数值
## `@each $var in <list or map>`

``` scss
$font: (size: 2rem, style: italic);

@each $key, $value in $font {
  p {font-#{$key}: $value};
}
```

``` css
p {
  font-size: 2rem; }

p {
  font-style: italic; }
```
